# Generated by Django 2.0.7 on 2019-01-11 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50, null=True, verbose_name='所属项目')),
                ('ipaddr', models.CharField(max_length=15, null=True, verbose_name='IP地址')),
                ('username', models.CharField(max_length=10, null=True, verbose_name='MySQL用户名')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='MySQL密码')),
                ('port', models.CharField(default=3306, max_length=5, verbose_name='MySQL端口')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_DataBaseInfo', 'can view DataBaseInfo'),),
            },
        ),
        migrations.CreateModel(
            name='IDCInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='机房名称')),
                ('position', models.CharField(max_length=50, verbose_name='机房位置')),
                ('status', models.CharField(max_length=50, verbose_name='状态')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_idcinfo', 'can view idcinfo'),),
            },
        ),
        migrations.CreateModel(
            name='RepoUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('repo_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='项目描述')),
                ('repo_type', models.CharField(blank=True, choices=[('前端', '前端'), ('后端', '后端'), ('接口', '接口')], max_length=30, null=True, verbose_name='项目类型')),
                ('repo_source_type', models.CharField(choices=[('svn', 'svn'), ('git', 'git')], max_length=5, verbose_name='版本库类型')),
                ('repo_source_address', models.CharField(max_length=200, verbose_name='库地址')),
                ('repo_user', models.CharField(max_length=50, verbose_name='库用户名')),
                ('repo_password', models.CharField(blank=True, max_length=50, verbose_name='库密码')),
                ('server_path', models.CharField(max_length=50, verbose_name='远程部署路径')),
                ('server_ip', models.CharField(max_length=500, verbose_name='服务器IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.CharField(max_length=15, null=True, verbose_name='IP地址')),
                ('username', models.CharField(max_length=10, null=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, null=True, verbose_name='密码')),
                ('port', models.CharField(default=22, max_length=5, verbose_name='端口')),
                ('keyfile', models.SmallIntegerField(blank=True, null=True, verbose_name='密钥')),
                ('servername', models.CharField(max_length=50, verbose_name='服务器名称')),
                ('system', models.CharField(max_length=30, verbose_name='操作系统')),
                ('role', models.CharField(max_length=50, null=True, verbose_name='服务器用途')),
                ('project', models.CharField(max_length=50, null=True, verbose_name='所属项目')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_serverinfo', 'can view serverinfo'),),
            },
        ),
    ]
