# Generated by Django 2.0.7 on 2020-03-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpuInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.CharField(max_length=16, verbose_name='IP地址')),
                ('cpu', models.CharField(max_length=50, verbose_name='cpu值')),
                ('status', models.CharField(max_length=50, verbose_name='健康状态')),
            ],
            options={
                'permissions': (('view_cpuinfo', 'can view cpuinfo'),),
            },
        ),
        migrations.AlterField(
            model_name='repoupgrade',
            name='server_ip',
            field=models.CharField(max_length=500, verbose_name='远程服务器IP'),
        ),
    ]
